using System.Collections.Generic;
using PhoenixAdult.Providers.Sites;

namespace PhoenixAdult.Providers
{
    public static class PhoenixAdultList
    {
        public static readonly Dictionary<int, Dictionary<int, string[]>> SiteList = new Dictionary<int, Dictionary<int, string[]>> {{
                    0, new Dictionary<int, string[]> {
                        {0, new string [] { "Brazzers", "https://www.brazzers.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "Asses In Public" } },
                        {2, new string [] { "Baby Got Boobs" } },
                        {3, new string [] { "Big Butts Like It Big" } },
                        {4, new string [] { "Big Tits at School" } },
                        {5, new string [] { "Big Tits at Work" } },
                        {6, new string [] { "Big Tits in Sports" } },
                        {7, new string [] { "Big Tits in Uniform" } },
                        {8, new string [] { "Big Wet Butts" } },
                        {9, new string [] { "Busty and Real" } },
                        {10, new string [] { "Busty Z" } },
                        {11, new string [] { "Butts and Blacks" } },
                        {12, new string [] { "CFNM Clothed Female Male Nude" } },
                        {13, new string [] { "Day With A Porn Star" } },
                        {14, new string [] { "Dirty Masseur" } },
                        {15, new string [] { "Doctor Adventures" } },
                        {16, new string [] { "Brazzers Exxtra" } },
                        {17, new string [] { "Hot and Mean" } },
                        {18, new string [] { "Hot Chicks Big Asses" } },
                        {19, new string [] { "Milfs Like It Big" } },
                        {20, new string [] { "Mommy Got Boobs" } },
                        {21, new string [] { "Moms in Control" } },
                        {22, new string [] { "Pornstars Like It Big" } },
                        {23, new string [] { "Racks and Blacks" } },
                        {24, new string [] { "Real Wife Stories" } },
                        {25, new string [] { "Shes Gonna Squirt" } },
                        {26, new string [] { "Teens Like It Big" } },
                        {27, new string [] { "Teens Like It Black" } },
                        {28, new string [] { "ZZ Series" } },
                    }
                },{
                    1, new Dictionary<int, string[]> {
                        {0, new string [] { "Bang", "https://www.bang.com", "https://617fb597b659459bafe6472470d9073a.us-east-1.aws.found.io/videos/video/_search" } },
                    }
                },{
                    2, new Dictionary<int, string[]> {
                        {0, new string [] { "Bellesa Films","https://www.bellesafilms.com/", "https://site-api.project1service.com" } },
                        {1, new string [] { "Bellesa House" } },
                        {2, new string [] { "Property Sex", "https://www.propertysex.com" } },
                        {3, new string [] { "TransAngels", "https://www.transangels.com" } },
                        {4, new string [] { "FamilyHookups", "https://www.familyhookups.com" } },
                        {5, new string [] { "Erito", "https://www.erito.com" } },
                        {6, new string [] { "Look At Her Now", "https://www.lookathernow.com" } },
                        {7, new string [] { "Bi Empire", "https://www.biempire.com" } },
                        {8, new string [] { "Deviant Hardcore", "https://www.devianthardcore.com" } },
                        {9, new string [] { "She Will Cheat", "https://www.shewillcheat.com" } },
                        {10, new string [] { "Kinky Spa", "https://www.kinkyspa.com/" } },
                        {11, new string [] { "Transsensual", "https://www.transsensual.com/" } },
                        {12, new string [] { "Lil Humpers", "https://www.lilhumpers.com" } },
                        {13, new string [] { "Family Sinners", "https://www.familysinners.com" } },
                        {14, new string [] { "DigitalPlayground", "https://www.digitalplayground.com" } },
                    }
                },{
                    3, new Dictionary<int, string[]> {
                        {0, new string [] { "Reality Kings", "https://www.realitykings.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "40 Inch Plus" } },
                        {2, new string [] { "8th Street Latinas" } },
                        {3, new string [] { "Bad Tow Truck" } },
                        {4, new string [] { "Big Naturals" } },
                        {5, new string [] { "Big Tits Boss" } },
                        {6, new string [] { "Bikini Crashers" } },
                        {7, new string [] { "Captain Stabbin" } },
                        {8, new string [] { "CFNM Secret" } },
                        {9, new string [] { "Cum Fiesta" } },
                        {10, new string [] { "Cum Girls" } },
                        {11, new string [] { "Dangerous Dongs" } },
                        {12, new string [] { "Euro Sex Parties" } },
                        {13, new string [] { "Extreme Asses" } },
                        {14, new string [] { "Extreme Naturals" } },
                        {15, new string [] { "First Time Auditions" } },
                        {16, new string [] { "Flower Tucci" } },
                        {17, new string [] { "Girls of Naked" } },
                        {18, new string [] { "Happy Tugs" } },
                        {19, new string [] { "HD Love" } },
                        {20, new string [] { "Hot Bush" } },
                        {21, new string [] { "In the VIP" } },
                        {22, new string [] { "Mike in Brazil" } },
                        {23, new string [] { "Mikes Apartment" } },
                        {24, new string [] { "Milf Hunter" } },
                        {25, new string [] { "Milf Next Door" } },
                        {26, new string [] { "Moms Bang Teens" } },
                        {27, new string [] { "Moms Lick Teens" } },
                        {28, new string [] { "Money Talks" } },
                        {29, new string [] { "Monster Curves" } },
                        {30, new string [] { "No Faces" } },
                        {31, new string [] { "Pure 18" } },
                        {32, new string [] { "Real Orgasms" } },
                        {33, new string [] { "RK Prime" } },
                        {34, new string [] { "Round and Brown" } },
                        {35, new string [] { "Saturday Night Latinas" } },
                        {36, new string [] { "See My Wife" } },
                        {37, new string [] { "Sneaky Sex" } },
                        {38, new string [] { "Street BlowJobs" } },
                        {39, new string [] { "Team Squirt" } },
                        {40, new string [] { "Teens Love Huge Cocks" } },
                        {41, new string [] { "Top Shelf Pussy" } },
                        {42, new string [] { "Tranny Surprise" } },
                        {43, new string [] { "VIP Crew" } },
                        {44, new string [] { "We Live Together" } },
                        {45, new string [] { "Wives in Pantyhose" } },
                        {46, new string [] { "GF Revenge" } },
                        {47, new string [] { "Black GFs" } },
                        {48, new string [] { "Dare Dorm" } },
                        {49, new string [] { "Crazy Asian GFs" } },
                        {50, new string [] { "Crazy College GFs" } },
                        {51, new string [] { "Horny Birds" } },
                        {52, new string [] { "Reckless in Miami" } },
                    }
                },{
                    4, new Dictionary<int, string[]> {
                        {0, new string [] { "Mofos", "https://www.mofos.com", "https://617fb597b659459bafe6472470d9073a.us-east-1.aws.found.io/videos/video/_search" } },
                        {1, new string [] { "ShareMyBF" } },
                        {2, new string [] { "Don't Break Me" } },
                        {3, new string [] { "I Know That Girl" } },
                        {4, new string [] { "Let's Try Anal" } },
                        {5, new string [] { "Pervs On Patrol" } },
                        {6, new string [] { "Stranded Teens" } },
                        {7, new string [] { "Mofos B Sides" } },
                        {8, new string [] { "Shes a Freak" } },
                        {9, new string [] { "Public Pickups" } },
                        {10, new string [] { "Latina Sex Tapes" } },
                        {11, new string [] { "Girls Gone Pink" } },
                        {12, new string [] { "Real Slut Party" } },
                        {13, new string [] { "Mofos Lab" } },
                    }
                },{
                    5, new Dictionary<int, string[]> {
                        {0, new string [] { "Twistys", "https://www.twistys.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "WhenGirlsPlay" } },
                        {2, new string [] { "MomKnowsBest" } },
                        {3, new string [] { "TwistysHard" } },
                        {4, new string [] { "TurningTwistys" } },
                    }
                },{
                    6, new Dictionary<int, string[]> {
                        {0, new string [] { "Babes", "https://www.babes.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "Babes Unleashed" } },
                        {2, new string [] { "Black is Better" } },
                        {3, new string [] { "Elegant Anal" } },
                        {4, new string [] { "Office Obsession" } },
                        {5, new string [] { "Stepmom Lessons" } },
                    }
                },{
                    7, new Dictionary<int, string[]> {
                        {0, new string [] { "SexyHub", "https://www.sexyhub.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "Dane Jones" } },
                        {2, new string [] { "Fitness Rooms" } },
                        {3, new string [] { "Girlfriends.xxx" } },
                        {4, new string [] { "Lesbea" } },
                        {5, new string [] { "Massage Rooms" } },
                        {6, new string [] { "MomXXX" } },
                    }
                },{
                    8, new Dictionary<int, string[]> {
                        {0, new string [] { "FakeHub", "https://www.fakehub.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "Fake Taxi" } },
                        {2, new string [] { "Fakehub Originals" } },
                        {3, new string [] { "Public Agent" } },
                        {4, new string [] { "Fake Agent" } },
                        {5, new string [] { "Female Agent" } },
                        {6, new string [] { "Fake Hospital" } },
                        {7, new string [] { "Fake Agent UK" } },
                        {8, new string [] { "Fake Cop" } },
                        {9, new string [] { "Female Fake Taxi" } },
                        {10, new string [] { "Fake Driving School" } },
                        {11, new string [] { "Fake Hostel" } },
                    }
                },{
                    9, new Dictionary<int, string[]> {
                        {0, new string [] { "Sweetheart Video", "https://www.milehighmedia.com", "https://site-api.project1service.com" } },
                        {1, new string [] { "Reality Junkies" } },
                        {2, new string [] { "SweetSinner" } },
                        {3, new string [] { "Doghouse Digital" } },
                    }
                },{
                    10, new Dictionary<int, string[]> {
                        {0, new string [] { "Naughty America", "https://www.naughtyamerica.com/", "https://i6p9q9r18e-3.algolianet.com/1/indexes/*/queries" } },
                        {1, new string [] { "My Friends Hot Mom" } },
                        {2, new string [] { "My First Sex Teacher" } },
                        {3, new string [] { "Seduced By A Cougar" } },
                        {4, new string [] { "My Daughters Hot Friend" } },
                        {5, new string [] { "My Wife is My Pornstar" } },
                        {6, new string [] { "Tonights Girlfriend Classic" } },
                        {7, new string [] { "Wives on Vacation" } },
                        {8, new string [] { "My Sisters Hot Friend" } },
                        {9, new string [] { "Naughty Weddings" } },
                        {10, new string [] { "Dirty Wives Club" } },
                        {11, new string [] { "My Dads Hot Girlfriend" } },
                        {12, new string [] { "My Girl Loves Anal" } },
                        {13, new string [] { "Lesbian Girl on Girl" } },
                        {14, new string [] { "Naughty Office" } },
                        {15, new string [] { "I have a Wife" } },
                        {16, new string [] { "Naughty Bookworms" } },
                        {17, new string [] { "Housewife 1 on 1" } },
                        {18, new string [] { "My Wifes Hot Friend" } },
                        {19, new string [] { "Latin Adultery" } },
                        {20, new string [] { "Ass Masterpiece" } },
                        {21, new string [] { "2 Chicks Same Time" } },
                        {22, new string [] { "My Friends Hot Girl" } },
                        {23, new string [] { "Neighbor Affair" } },
                        {24, new string [] { "My Girlfriends Busty Friend" } },
                        {25, new string [] { "Naughty Athletics" } },
                        {26, new string [] { "My Naughty Massage" } },
                        {27, new string [] { "Fast Times" } },
                        {28, new string [] { "The Passenger" } },
                        {29, new string [] { "Milf Sugar Babes Classic" } },
                        {30, new string [] { "Perfect Fucking Strangers Classic" } },
                        {31, new string [] { "Asian 1 on 1" } },
                        {32, new string [] { "American Daydreams" } },
                        {33, new string [] { "SoCal Coeds" } },
                        {34, new string [] { "Naughty Country Girls" } },
                        {35, new string [] { "Diary of a Milf" } },
                        {36, new string [] { "Naughty Rich Girls" } },
                        {37, new string [] { "My Naughty Latin Maid" } },
                        {38, new string [] { "Diary of a Nanny" } },
                        {39, new string [] { "Naughty Flipside" } },
                        {40, new string [] { "Live Party Girl" } },
                        {41, new string [] { "Live Naughty Student" } },
                        {42, new string [] { "Live Naughty Secretary" } },
                        {43, new string [] { "Live Gym Cam" } },
                        {44, new string [] { "Live Naughty Teacher" } },
                        {45, new string [] { "Live Naughty Milf" } },
                        {46, new string [] { "Live Naughty Nurse" } },
                        {47, new string [] { "Big Cock Bully" } },
                        {48, new string [] { "LA Sluts" } },
                        {49, new string [] { "Slut Stepsister" } },
                        {50, new string [] { "Teens Love Cream" } },
                        {51, new string [] { "Latina Stepmom" } },
                        {52, new string [] { "Anal College" } },
                        {53, new string [] { "Watch Your Wife" } },
                        {54, new string [] { "Slut Stepmom" } },
                        {55, new string [] { "Sleazy Stepdad" } },
                        {56, new string [] { "Open Family" } },
                        {57, new string [] { "Watch Your Mom" } },
                        {58, new string [] { "Show My BF" } },
                        {59, new string [] { "Naughty America VR" } },
                    }
                },{
                    11, new Dictionary<int, string[]> {
                        {0, new string [] { "Adult Time", "https://freetour.adulttime.com", "https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries" } },
                        {1, new string [] { "Evil Angel", "https://www.evilangel.com" } },
                        {2, new string [] { "Pure Taboo", "https://www.puretaboo.com" } },
                        {3, new string [] { "Burning Angel", "https://www.burningangel.com" } },
                        {4, new string [] { "Devil's Film", "https://www.devilsfilm.com" } },
                        {5, new string [] { "Rocco Siffredi", "https://www.roccosiffredi.com" } },
                        {6, new string [] { "Gender X", "https://www.genderx.com" } },
                    }
                },{
                    12, new Dictionary<int, string[]> {
                        {0, new string [] { "Girlsway", "https://www.girlsway.com", "https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries" } },
                        {1, new string [] { "Mommys Girl" } },
                        {2, new string [] { "Web Young" } },
                        {3, new string [] { "Girls Try Anal" } },
                        {4, new string [] { "Sextape Lesbians" } },
                        {5, new string [] { "Girlsway Originals" } },
                        {6, new string [] { "GirlCore" } },
                        {7, new string [] { "Moms On Moms" } },
                        {8, new string [] { "We Like Girls" } },
                    }
                },{
                    13, new Dictionary<int, string[]> {
                        {0, new string [] { "21Naturals", "https://www.21naturals.com", "https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries" } },
                        {1, new string [] { "21FootArt" } },
                        {2, new string [] { "21EroticAnal" } },
                    }
                },{
                    14, new Dictionary<int, string[]> {
                        {0, new string [] { "21Sextury", "https://www.21sextury.com", "https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries" } },
                        {1, new string [] { "Anal Teen Angels" } },
                        {2, new string [] { "Deepthroat Frenzy" } },
                        {3, new string [] { "DP Fanatics" } },
                        {4, new string [] { "Footsie Babes" } },
                        {5, new string [] { "Gapeland" } },
                        {6, new string [] { "Lez Cuties" } },
                        {7, new string [] { "Pix and Video" } },
                        {8, new string [] { "Asshole Fever" } },
                        {9, new string [] { "Butt Plays" } },
                    }
                },{
                    15, new Dictionary<int, string[]> {
                        {0, new string [] { "21Sextreme", "https://www.21sextreme.com", "https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries" } },
                        {1, new string [] { "LustyGrandmas" } },
                        {2, new string [] { "GrandpasFuckTeens" } },
                        {3, new string [] { "TeachMeFisting" } },
                        {4, new string [] { "Zoliboy" } },
                        {5, new string [] { "DominatedGirls" } },
                    }
                },{
                    16, new Dictionary<int, string[]> {
                        {0, new string [] { "Kink", "https://www.kink.com", "https://www.kink.com/search?q=" } },
                        {1, new string [] { "Brutal Sessions" } },
                        {2, new string [] { "Device Bondage" } },
                        {3, new string [] { "Families Tied" } },
                        {4, new string [] { "Hardcore Gangbang" } },
                        {5, new string [] { "Hogtied" } },
                        {6, new string [] { "Kink Features" } },
                        {7, new string [] { "Kink University" } },
                        {8, new string [] { "Public Disgrace" } },
                        {9, new string [] { "Sadistic Rope" } },
                        {10, new string [] { "Sex and Submission" } },
                        {11, new string [] { "The Training of O" } },
                        {12, new string [] { "The Upper Floor" } },
                        {13, new string [] { "Water Bondage" } },
                        {14, new string [] { "Everything Butt" } },
                        {15, new string [] { "Foot Worship" } },
                        {16, new string [] { "Fucking Machines" } },
                        {17, new string [] { "TS Pussy Hunters" } },
                        {18, new string [] { "TS Seduction" } },
                        {19, new string [] { "Ultimate Surrender" } },
                        {20, new string [] { "30 Minutes of Torment" } },
                        {21, new string [] { "Bound Gods" } },
                        {22, new string [] { "Bound in Public" } },
                        {23, new string [] { "Butt Machine Boys" } },
                        {24, new string [] { "Men on Edge" } },
                        {25, new string [] { "Naked Kombat" } },
                        {26, new string [] { "Divine Bitches" } },
                        {27, new string [] { "Electrosluts" } },
                        {28, new string [] { "Men in Pain" } },
                        {29, new string [] { "Whipped Ass" } },
                        {30, new string [] { "Wired Pussy" } },
                        {31, new string [] { "Bound Gang Bangs" } },
                        {32, new string [] { "Chantas Bitches" } },
                        {33, new string [] { "Fucked and Bound" } },
                        {34, new string [] { "Captive Male" } },
                        {35, new string [] { "SubmissiveX" } },
                        {36, new string [] { "Filthy Femdom" } },
                    }
                },{
                    17, new Dictionary<int, string[]> {
                        {0, new string [] { "JAV", "https://www.r18.com", "https://www.r18.com/common/search/searchword=" } },
                    }
                },{
                    18, new Dictionary<int, string[]> {
                        {0, new string [] { "Femdom Empire", "https://femdomempire.com", "https://femdomempire.com/tour/search.php?st=advanced&qany=" } },
                        {1, new string [] { "Feminized", "http://feminized.com", "http://feminized.com/tour/search.php?st=advanced&qany=" } },
                    }
                },{
                    19, new Dictionary<int, string[]> {
                        {0, new string [] { "Dogfart", "https://www.dogfartnetwork.com", "https://www.dogfartnetwork.com/tour/search.php?search=" } },
                        {1, new string [] { "BlacksOnBlondes" } },
                        {2, new string [] { "CuckoldSessions" } },
                        {3, new string [] { "GloryHole" } },
                        {4, new string [] { "BlacksOnCougars" } },
                        {5, new string [] { "WeFuckBlackGirls" } },
                        {6, new string [] { "WatchingMyMomGoBlack" } },
                        {7, new string [] { "InterracialBlowbang" } },
                        {8, new string [] { "CumBang" } },
                        {9, new string [] { "InterracialPickups" } },
                        {10, new string [] { "WatchingMyDaughterGoBlack" } },
                        {11, new string [] { "ZebraGirls" } },
                        {12, new string [] { "GloryHoleInitiations" } },
                        {13, new string [] { "DogfartBehindTheScenes" } },
                        {14, new string [] { "BlackMeatWhiteFeet" } },
                        {15, new string [] { "SpringThomas" } },
                        {16, new string [] { "KatieThomas" } },
                        {17, new string [] { "RuthBlackwell" } },
                        {18, new string [] { "CandyMonroe" } },
                        {19, new string [] { "WifeWriting" } },
                        {20, new string [] { "BarbCummings" } },
                        {21, new string [] { "TheMinion" } },
                        {22, new string [] { "BlacksOnBoys" } },
                        {23, new string [] { "GloryholesAndHandjobs" } },
                    }
                },{
                    20, new Dictionary<int, string[]> {
                        {0, new string [] { "PornPros", "https://www.pornpros.com", "https://pornpros.com/video/" } },
                        {1, new string [] { "18YearsOld" } },
                        {2, new string [] { "RealExGirlfriends" } },
                        {3, new string [] { "MassageCreep" } },
                        {4, new string [] { "DeepThroatLove" } },
                        {5, new string [] { "TeenBFF" } },
                        {6, new string [] { "ShadyPi" } },
                        {7, new string [] { "CrueltyParty" } },
                        {8, new string [] { "Disgraced18" } },
                        {9, new string [] { "MilfHumiliation" } },
                        {10, new string [] { "CumshotSurprise" } },
                        {11, new string [] { "40ozBounce" } },
                        {12, new string [] { "JurassicCock" } },
                        {13, new string [] { "FreaksOfCock" } },
                        {14, new string [] { "EuroHumpers" } },
                        {15, new string [] { "FreaksOfBoobs" } },
                        {16, new string [] { "CumDisgrace" } },
                        {17, new string [] { "CockCompetition" } },
                        {18, new string [] { "PimpParade" } },
                        {19, new string [] { "SquirtDisgrace" } },
                    }
                },{
                    21, new Dictionary<int, string[]> {
                        {0, new string [] { "POVD", "https://www.povd.com", "https://povd.com/video/" } },
                        {1, new string [] { "Cum4K", "https://www.cum4k.com", "https://cum4k.com/video/" } },
                        {2, new string [] { "Exotic4k", "https://www.exotic4k.com", "https://exotic4k.com/video/" } },
                        {3, new string [] { "Tiny4k", "https://www.tiny4k.com", "https://tiny4k.com/video/" } },
                        {4, new string [] { "Lubed", "https://www.lubed.com", "https://lubed.com/video/" } },
                        {5, new string [] { "PureMature", "https://www.puremature.com", "https://puremature.com/video/" } },
                        {6, new string [] { "NannySpy", "https://www.nannyspy.com", "https://nannyspy.com/video/" } },
                        {7, new string [] { "Holed", "https://www.holed.com", "https://holed.com/video/" } },
                        {8, new string [] { "CastingCouch-X", "https://www.castingcouch-x.com", "https://castingcouch-x.com/video/" } },
                        {9, new string [] { "SpyFam", "https://www.spyfam.com", "https://spyfam.com/video/" } },
                        {10, new string [] { "MyVeryFirstTime", "https://www.myveryfirsttime.com", "https://myveryfirsttime.com/video/" } },
                        {11, new string [] { "Baeb", "https://www.baeb.com", "https://baeb.com/video/" } },
                        {12, new string [] { "GirlCum", "https://www.girlcum.com", "https://www.girlcum.com/video/" } },
                        {13, new string [] { "BBCPie", "https://bbcpie.com", "https://bbcpie.com/video/" } },
                    }
                },{
                    22, new Dictionary<int, string[]> {
                        {0, new string [] { "Bang Bros", "https://bangbros.com", "https://bangbros.com/search/" } },
                        {1, new string [] { "Ass Parade" } },
                        {2, new string [] { "AvaSpice" } },
                        {3, new string [] { "Back Room Facials" } },
                        {4, new string [] { "Backroom MILF" } },
                        {5, new string [] { "Ball Honeys" } },
                        {6, new string [] { "Bang Bus" } },
                        {7, new string [] { "Bang Casting" } },
                        {8, new string [] { "Bang POV" } },
                        {9, new string [] { "Bang Tryouts" } },
                        {10, new string [] { "BangBros 18" } },
                        {11, new string [] { "BangBros Angels" } },
                        {12, new string [] { "Bangbros Clips" } },
                        {13, new string [] { "BangBros Remastered" } },
                        {14, new string [] { "Big Mouthfuls" } },
                        {15, new string [] { "Big Tit Cream Pie" } },
                        {16, new string [] { "Big Tits Round Asses" } },
                        {17, new string [] { "BlowJob Fridays" } },
                        {18, new string [] { "Blowjob Ninjas" } },
                        {19, new string [] { "Boob Squad" } },
                        {20, new string [] { "Brown Bunnies" } },
                        {21, new string [] { "Can He Score" } },
                        {22, new string [] { "Bang Casting" } },
                        {23, new string [] { "Chongas" } },
                        {24, new string [] { "Colombia Fuck Fest" } },
                        {25, new string [] { "Dirty World Tour" } },
                        {26, new string [] { "Dorm Invasion" } },
                        {27, new string [] { "Facial Fest" } },
                        {28, new string [] { "Fuck Team Five" } },
                        {29, new string [] { "Glory Hole Loads" } },
                        {30, new string [] { "Latina Rampage" } },
                        {31, new string [] { "Living With Anna" } },
                        {32, new string [] { "Magical Feet" } },
                        {33, new string [] { "MILF Lessons" } },
                        {34, new string [] { "Milf Soup" } },
                        {35, new string [] { "MomIsHorny" } },
                        {36, new string [] { "Monsters of Cock" } },
                        {37, new string [] { "Mr CamelToe" } },
                        {38, new string [] { "Mr Anal" } },
                        {39, new string [] { "My Dirty Maid" } },
                        {40, new string [] { "My Life In Brazil" } },
                        {41, new string [] { "Newbie Black" } },
                        {42, new string [] { "Party of 3" } },
                        {43, new string [] { "Pawg" } },
                        {44, new string [] { "Penny Show" } },
                        {45, new string [] { "Porn Star Spa" } },
                        {46, new string [] { "Power Munch" } },
                        {47, new string [] { "Public Bang" } },
                        {48, new string [] { "Slutty White Girls" } },
                        {49, new string [] { "Stepmom Videos" } },
                        {50, new string [] { "Street Ranger" } },
                        {51, new string [] { "Tugjobs" } },
                        {52, new string [] { "Working Latinas" } },
                    }
                },{
                    23, new Dictionary<int, string[]> {
                        {0, new string [] { "Mylf", "https://mylf.com", "https://www.mylf.com/movies/" } },
                        {1, new string [] { "MylfBoss" } },
                        {2, new string [] { "MylfBlows" } },
                        {3, new string [] { "Milfty" } },
                        {4, new string [] { "Got Mylf" } },
                        {5, new string [] { "Mom Drips" } },
                        {6, new string [] { "Mylfed" } },
                        {7, new string [] { "Milf Body" } },
                        {8, new string [] { "Lone Milf" } },
                        {9, new string [] { "Full Of JOI" } },
                        {10, new string [] { "Mylfwood" } },
                        {11, new string [] { "ShoplyfterMylf", "https://www.shoplyftermylf.com", "https://www.shoplyftermylf.com/movies/" } },
                        {12, new string [] { "Mylf x Joybear" } },
                        {13, new string [] { "Mylf x Teamskeet" } },
                        {14, new string [] { "Mylf x Hussie Pass" } },
                        {15, new string [] { "Mylf Of The Month" } },
                        {16, new string [] { "Mylfselects" } },
                        {17, new string [] { "Mylf x Lady Fyre" } },
                        {18, new string [] { "Mylf X CamSoda" } },
                        {19, new string [] { "Mylf X Fucking Awesome" } },
                        {20, new string [] { "Mylf X James Deen" } },
                        {21, new string [] { "Mylf X Mindi Mink" } },
                        {22, new string [] { "Mylf X Owen Gray" } },
                        {23, new string [] { "Mylf X SpankMonster" } },
                        {24, new string [] { "StayHomeMilf" } },
                        {25, new string [] { "Mylfdom", "https://www.mylfdom.com", "https://www.mylfdom.com/movies/" } },
                    }
                },{
                    24, new Dictionary<int, string[]> {
                        {0, new string [] { "TeamSkeet", "https://www.teamskeet.com", "https://www.teamskeet.com/movies/" } },
                        {1, new string [] { "Exxxtra Small", "https://www.exxxtrasmall.com", "https://www.exxxtrasmall.com/movies/" } },
                        {2, new string [] { "Teen Pies", "https://www.teenpies.com", "https://www.teenpies.com/movies/" } },
                        {3, new string [] { "Innocent High", "https://www.innocenthigh.com", "https://www.innocenthigh.com/movies/" } },
                        {4, new string [] { "Teen Curves", "https://www.teencurves.com/", "https://www.teencurves.com/movies/" } },
                        {5, new string [] { "CFNM Teens" } },
                        {6, new string [] { "Teens Love Anal", "https://www.teensloveanal.com", "https://www.teensloveanal.com/movies/" } },
                        {7, new string [] { "My Babysitters Club", "https://www.mybabysittersclub.com", "https://www.mybabysittersclub.com/movies/" } },
                        {8, new string [] { "She's New" } },
                        {9, new string [] { "Teens Do Porn" } },
                        {10, new string [] { "POV Life" } },
                        {11, new string [] { "The Real Workout" } },
                        {12, new string [] { "This Girl Sucks" } },
                        {13, new string [] { "Teens Love Money" } },
                        {14, new string [] { "Oye Loca" } },
                        {15, new string [] { "Titty Attack" } },
                        {16, new string [] { "Teeny Black" } },
                        {17, new string [] { "Lust HD" } },
                        {18, new string [] { "Rub A Teen" } },
                        {19, new string [] { "Her Freshman Year" } },
                        {20, new string [] { "Self Desire" } },
                        {21, new string [] { "Solo Interviews" } },
                        {22, new string [] { "Team Skeet Extras" } },
                        {23, new string [] { "Dyked", "https://www.dyked.com", "https://www.dyked.com/movies/" } },
                        {24, new string [] { "Badmilfs", "https://www.badmilfs.com", "https://www.badmilfs.com/movies/" } },
                        {25, new string [] { "Gingerpatch" } },
                        {26, new string [] { "BraceFaced" } },
                        {27, new string [] { "TeenJoi", "https://www.teenjoi.com", "https://www.teenjoi.com/movies/" } },
                        {28, new string [] { "StepSiblings", "https://www.stepsiblings.com", "https://www.stepsiblings.com/movies/" } },
                        {29, new string [] { "Black Valley Girls", "https://www.blackvalleygirls.com", "https://www.blackvalleygirls.com/movies/" } },
                        {30, new string [] { "Sis Loves Me", "https://www.sislovesme.com", "https://www.sislovesme.com/movies/" } },
                        {31, new string [] { "Family Strokes", "https://www.familystrokes.com", "https://www.familystrokes.com/movies/" } },
                        {32, new string [] { "PervMom", "https://www.pervmom.com", "https://www.pervmom.com/movies/" } },
                        {33, new string [] { "DadCrush", "https://www.dadcrush.com", "https://www.dadcrush.com/movies/" } },
                        {34, new string [] { "DaughterSwap", "https://www.daughterswap.com", "https://www.daughterswap.com/movies/" } },
                        {35, new string [] { "Foster Tapes", "https://www.fostertapes.com", "https://www.fostertapes.com/movies/" } },
                        {36, new string [] { "BFFs", "https://www.bffs.com", "https://www.bffs.com/movies/" } },
                        {37, new string [] { "Shoplyfter", "https://www.shoplyfter.com", "https://www.shoplyfter.com/movies/" } },
                        {38, new string [] { "Little Asians", "https://www.littleasians.com", "https://www.littleasians.com/movies" } },
                        {39, new string [] { "Thickumz", "https://www.thickumz.com", "https://www.thickumz.com/movies/" } },
                        {40, new string [] { "Teens Love Black Cocks", "https://www.teensloveblackcocks.com", "https://www.teensloveblackcocks.com/movies/" } },
                        {41, new string [] { "Anal Mom", "https://analmom.com", "https://www.analmom.com/movies/" } },
                        {42, new string [] { "BBC Paradise", "https://www.bbcparadise.com/", "https://www.bbcparadise.com/movies/" } },
                    }
                },{
                    25, new Dictionary<int, string[]> {
                        {0, new string [] { "Jules Jordan", "https://www.julesjordan.com", "https://www.julesjordan.com/trial/search.php?query=" } },
                        {1, new string [] { "Manuel Ferrara", "https://www.manuelferrara.com", "https://www.manuelferrara.com/trial/search.php?query=" } },
                        {2, new string [] { "The Ass Factory", "https://www.theassfactory.com", "https://www.theassfactory.com/trial/search.php?query=" } },
                        {3, new string [] { "Sperm Swallowers", "https://www.spermswallowers.com", "https://www.spermswallowers.com/trial/search.php?query=" } },
                        {4, new string [] { "GirlGirl", "https://www.girlgirl.com", "https://www.girlgirl.com/trial/search.php?query=" } },
                    }
                },{
                    26, new Dictionary<int, string[]> {
                        {0, new string [] { "LegalPorno", "https://www.legalporno.com", "https://www.legalporno.com/search/?query=" } },
                    }
                }
            };

        public static readonly Dictionary<string, string> AbbrieviationList = new Dictionary<string, string> {
            { @"^18og ", "18OnlyGirls " },
            { @"^18yo ", "18YearsOld " },
            { @"^1kf ", "1000Facials " },
            { @"^21ea ", "21EroticAnal " },
            { @"^21fa ", "21FootArt " },
            { @"^21n ", "21Naturals " },
            { @"^2cst ", "2ChicksSameTime " },
            { @"^a1o1 ", "Asian1on1 " },
            { @"^aa ", "AmateurAllure " },
            { @"^ad ", "AmericanDaydreams " },
            { @"^add ", "ManualAddActors " },
            { @"^agm ", "AllGirlMassage " },
            { @"^am ", "AssMasterpiece " },
            { @"^analb ", "AnalBeauty " },
            { @"^ap ", "AssParade " },
            { @"^baebz ", "Baeb " },
            { @"^bblib ", "BigButtsLikeItBig " },
            { @"^bcasting ", "BangCasting " },
            { @"^bcb ", "BigCockBully " },
            { @"^bch ", "BigCockHero " },
            { @"^bconfessions ", "BangConfessions " },
            { @"^bdpov ", "BadDaddyPOV " },
            { @"^bex ", "BrazzersExxtra " },
            { @"^bgb ", "BabyGotBoobs " },
            { @"^bgbs ", "BoundGangbangs " },
            { @"^bglamkore ", "BangGlamkore " },
            { @"^bgonzo ", "BangGonzo " },
            { @"^bin ", "BigNaturals " },
            { @"^bjf ", "BlowjobFridays " },
            { @"^bp ", "ButtPlays " },
            { @"^brealteens ", "BangRealTeens " },
            { @"^btas ", "BigTitsatSchool " },
            { @"^btaw ", "BigTitsatWork " },
            { @"^btc", "BigTitCreampie " },
            { @"^btis ", "BigTitsinSports " },
            { @"^btiu ", "BigTitsinUniform " },
            { @"^btlbd ", "BigTitsLikeBigDicks " },
            { @"^btra ", "BigTitsRoundAsses " },
            { @"^burna ", "BurningAngel " },
            { @"^bwb ", "BigWetButts " },
            { @"^clip ", "LegalPorno " },
            { @"^cps ", "CherryPimps " },
            { @"^css ", "CzechStreets " },
            { @"^cuf ", "CumFiesta " },
            { @"^cws ", "CzechWifeSwap " },
            { @"^da ", "DoctorAdventures " },
            { @"^daughter ", "DaughterSwap " },
            { @"^daughters ", "DaughterSwap " },
            { @"^dbm ", "DontBreakMe " },
            { @"^dc ", "DorcelVision " },
            { @"^ddfb ", "DDFBusty " },
            { @"^dm ", "DirtyMasseur " },
            { @"^dnj ", "DaneJones " },
            { @"^dpg ", "DigitalPlayground " },
            { @"^dsw ", "DaughterSwap " },
            { @"^dwc ", "DirtyWivesClub " },
            { @"^dwp ", "DayWithAPornstar " },
            { @"^esp ", "EuroSexParties " },
            { @"^ete ", "EuroTeenErotica " },
            { @"^ext ", "ExxxtraSmall " },
            { @"^fams ", "FamilyStrokes " },
            { @"^faq ", "FirstAnalQuest " },
            { @"^fds ", "FakeDrivingSchool " },
            { @"^fft ", "FemaleFakeTaxi " },
            { @"^fhd ", "FantasyHD " },
            { @"^fhl ", "FakeHostel " },
            { @"^fho ", "FakehubOriginals " },
            { @"^fka ", "FakeAgent " },
            { @"^fm ", "FuckingMachines " },
            { @"^fms ", "FantasyMassage " },
            { @"^frs ", "FitnessRooms " },
            { @"^ft ", "FastTimes " },
            { @"^ftx ", "FakeTaxi " },
            { @"^gbcp ", "GangbangCreampie " },
            { @"^gft ", "GrandpasFuckTeens " },
            { @"^gta ", "GirlsTryAnal " },
            { @"^gw ", "GirlsWay " },
            { @"^h1o1 ", "Housewife1on1 " },
            { @"^ham ", "HotAndMean " },
            { @"^hart ", "Hegre " },
            { @"^hcm ", "HotCrazyMess " },
            { @"^hegre-art ", "Hegre " },
            { @"^hoh ", "HandsOnHardcore " },
            { @"^hotab ", "HouseofTaboo " },
            { @"^ht ", "Hogtied " },
            { @"^hustl3r ", "Hustler " },
            { @"^ihaw ", "IHaveAWife " },
            { @"^iktg ", "IKnowThatGirl " },
            { @"^il ", "ImmoralLive " },
            { @"^kha ", "KarupsHA " },
            { @"^kow ", "KarupsOW " },
            { @"^kpc ", "KarupsPC " },
            { @"^la ", "LatinAdultery " },
            { @"^latn ", "LookAtHerNow " },
            { @"^lcd ", "LittleCaprice " },
            { @"^lhf ", "LoveHerFeet " },
            { @"^lsb ", "Lesbea " },
            { @"^lst ", "LatinaSexTapes " },
            { @"^lta ", "LetsTryAnal " },
            { @"^maj ", "ManoJob " },
            { @"^mbb ", "MommyBlowsBest " },
            { @"^mbt ", "MomsBangTeens " },
            { @"^mc ", "MassageCreep " },
            { @"^mcu ", "MonsterCurves " },
            { @"^mdhf ", "MyDaughtersHotFriend " },
            { @"^mdhg ", "MyDadsHotGirlfriend " },
            { @"^mfa ", "ManuelFerrara " },
            { @"^mfhg ", "MyFriendsHotGirl " },
            { @"^mfhm ", "MyFriendsHotMom " },
            { @"^mfl ", "Mofos " },
            { @"^mfst ", "MyFirstSexTeacher " },
            { @"^mgb ", "MommyGotBoobs " },
            { @"^mgbf ", "MyGirlfriendsBustyFriend " },
            { @"^mic ", "MomsInControl " },
            { @"^mih ", "MilfHunter " },
            { @"^mj ", "ManoJob " },
            { @"^mlib ", "MilfsLikeItBig " },
            { @"^mlt ", "MomsLickTeens " },
            { @"^mmgs ", "MommysGirl " },
            { @"^mmts ", "MomsTeachSex " },
            { @"^mnm ", "MyNaughtyMassage " },
            { @"^mom ", "MomXXX " },
            { @"^mpov ", "MrPOV " },
            { @"^mr ", "MassageRooms " },
            { @"^mrs ", "MassageRooms " },
            { @"^mshf ", "MySistersHotFriend " },
            { @"^mts ", "MomsTeachSex " },
            { @"^mvft ", "MyVeryFirstTime " },
            { @"^mwhf ", "MyWifesHotFriend " },
            { @"^na ", "NaughtyAthletics " },
            { @"^naf ", "NeighborAffair " },
            { @"^nam ", "NaughtyAmerica " },
            { @"^nb ", "NaughtyBookworms " },
            { @"^news ", "NewSensations " },
            { @"^nf ", "NubileFilms " },
            { @"^no ", "NaughtyOffice " },
            { @"^nrg ", "NaughtyRichGirls " },
            { @"^nubilef ", "NubileFilms " },
            { @"^num ", "NuruMassage " },
            { @"^nw ", "NaughtyWeddings " },
            { @"^obj ", "OnlyBlowjob " },
            { @"^otb ", "OnlyTeenBlowjobs " },
            { @"^pav ", "PixAndVideo " },
            { @"^pba ", "PublicAgent " },
            { @"^pc ", "PrincessCum " },
            { @"^pdmcl ", "ChicasLoca " },
            { @"^pf ", "PornFidelity " },
            { @"^phd ", "PassionHD " },
            { @"^phdp ", "PetiteHDPorn " },
            { @"^plib ", "PornstarsLikeitBig " },
            { @"^pop ", "PervsOnPatrol " },
            { @"^ppu ", "PublicPickups " },
            { @"^prdi ", "PrettyDirty " },
            { @"^ps ", "PropertySex " },
            { @"^ptt ", "Petite " },
            { @"^pud ", "PublicDisgrace " },
            { @"^reg ", "RealExGirlfriends " },
            { @"^rkp ", "RKPrime " },
            { @"^rws ", "RealWifeStories " },
            { @"^saf ", "ShesAFreak " },
            { @"^sart ", "SexArt " },
            { @"^sas ", "SexandSubmission " },
            { @"^sbj ", "StreetBlowjobs " },
            { @"^sins ", "SinsLife " },
            { @"^sislove ", "SisLovesMe " },
            { @"^smb ", "ShareMyBF " },
            { @"^ssc ", "StepSiblingsCaught " },
            { @"^ssn ", "ShesNew " },
            { @"^sts ", "StrandedTeens " },
            { @"^swsn ", "SwallowSalon " },
            { @"^tdp ", "TeensDoPorn " },
            { @"^tds ", "TheDickSuckers " },
            { @"^ted ", "Throated " },
            { @"^tf ", "TeenFidelity " },
            { @"^tgs ", "ThisGirlSucks " },
            { @"^these ", "TheStripperExperience " },
            { @"^tla ", "TeensLoveAnal " },
            { @"^tlc ", "TeensLoveCream " },
            { @"^tle ", "TheLifeErotic " },
            { @"^tlhc ", "TeensLoveHugeCocks " },
            { @"^tlib ", "TeensLikeItBig " },
            { @"^tlm ", "TeensLoveMoney " },
            { @"^tog ", "TonightsGirlfriend " },
            { @"^togc ", "TonightsGirlfriendClassic " },
            { @"^tspa ", "TrickySpa " },
            { @"^tss ", "ThatSitcomShow " },
            { @"^tuf ", "TheUpperFloor " },
            { @"^wa ", "WhippedAss " },
            { @"^wfbg ", "WeFuckBlackGirls " },
            { @"^wkp ", "Wicked " },
            { @"^wlt ", "WeLiveTogether " },
            { @"^woc ", "WildOnCam " },
            { @"^wov ", "WivesOnVacation " },
            { @"^wowg ", "WowGirls " },
            { @"^wy ", "WebYoung " },
            { @"^ztod ", "ZeroTolerance " },
            { @"^zzs ", "ZZseries " },
        };

        internal static IPhoenixAdultProviderBase GetProviderBySiteID(int siteID)
        {
            switch (siteID)
            {
                case 0: return new Network1service();
                case 1: return new NetworkBang();
                case 2: return new Network1service();
                case 3: return new Network1service();
                case 4: return new Network1service();
                case 5: return new Network1service();
                case 6: return new Network1service();
                case 7: return new Network1service();
                case 8: return new Network1service();
                case 9: return new Network1service();
                case 10: return new SiteNaughtyAmerica();
                case 11: return new NetworkGammaEnt();
                case 12: return new NetworkGammaEnt();
                case 13: return new NetworkGammaEnt();
                case 14: return new NetworkGammaEnt();
                case 15: return new NetworkGammaEnt();
                case 16: return new NetworkKink();
                case 17: return new NetworkR18();
                case 18: return new NetworkFemdomEmpire();
                case 19: return new NetworkDogfart();
                case 20: return new NetworkPornPros();
                case 21: return new NetworkPornPros();
                case 22: return new SiteBangBros();
                case 23: return new NetworkMylf();
                case 24: return new NetworkMylf();
                case 25: return new SiteJulesJordan();
                case 26: return new SiteLegalPorno();
                default: return null;
            };
        }
    }
}
