name: Build
on:
  push:
    branches:
      - master
    tags: ["v*"]
    paths:
      - Jellyfin.Plugin.PhoenixAdult/**
      - .github/**

jobs:
  jellyfin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: MSBuild -t:Restore,Build -p:RestorePackagesConfig=true -property:Configuration=Release

      - name: Rename Files
        run: ren Jellyfin.Plugin.PhoenixAdult/bin/Release/net8.0/PhoenixAdult.dll Jellyfin.Plugin.PhoenixAdult.dll && ren Jellyfin.Plugin.PhoenixAdult/bin/Release/net8.0/PhoenixAdult.pdb Jellyfin.Plugin.PhoenixAdult.pdb

      - uses: vimtor/action-zip@v1
        with:
          files: Jellyfin.Plugin.PhoenixAdult/bin/Release/net8.0/Jellyfin.Plugin.PhoenixAdult.pdb Jellyfin.Plugin.PhoenixAdult/bin/Release/net8.0/Jellyfin.Plugin.PhoenixAdult.dll
          dest: Jellyfin.Plugin.PhoenixAdult.zip

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Jellyfin
          retention-days: 90
          path: Jellyfin.Plugin.PhoenixAdult.zip
  emby:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: MSBuild -t:Restore,Build -p:RestorePackagesConfig=true -property:Configuration=Release.Emby

      - name: Rename Files
        run: ren Jellyfin.Plugin.PhoenixAdult/bin/Release.Emby/netstandard2.1/PhoenixAdult.dll ./Emby.Plugins.PhoenixAdult.dll && ren Jellyfin.Plugin.PhoenixAdult/bin/Release.Emby/netstandard2.1/PhoenixAdult.pdb ./Emby.Plugins.PhoenixAdult.pdb

      - uses: vimtor/action-zip@v1
        with:
          files: Jellyfin.Plugin.PhoenixAdult/bin/Release.Emby/netstandard2.1/Emby.Plugins.PhoenixAdult.pdb Jellyfin.Plugin.PhoenixAdult/bin/Release.Emby/netstandard2.1/Emby.Plugins.PhoenixAdult.dll
          dest: Emby.Plugins.PhoenixAdult.zip

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Emby
          retention-days: 90
          path: Emby.Plugins.PhoenixAdult.zip
  deploy:
    runs-on: ubuntu-latest
    needs: [jellyfin, emby]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            **/Jellyfin.Plugin.PhoenixAdult.zip
            **/Emby.Plugins.PhoenixAdult.zip
